-- MySQL Script generated by MySQL Workbench
-- Mon Nov  4 10:47:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dados` DEFAULT CHARACTER SET utf8 ;
USE `dados` ;

-- -----------------------------------------------------
-- Table `dados`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`usuarios` (
  `Username` VARCHAR(12) NOT NULL,
  `Password` VARCHAR(8) NULL DEFAULT NULL,
  `Tipo` INT(11) NULL DEFAULT NULL,
  `Dica` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dados`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`clientes` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `Tipo` INT(11) NULL DEFAULT NULL,
  `DTNascimento` VARCHAR(40) NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NULL DEFAULT NULL,
  `CNPJ` VARCHAR(14) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Telefone` VARCHAR(15) NULL DEFAULT NULL,
  `Username` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `usuarios_Username_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `usuarios_Username`
    FOREIGN KEY (`Username`)
    REFERENCES `dados`.`usuarios` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dados`.`locais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`locais` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Bairro` VARCHAR(45) NULL DEFAULT NULL,
  `Cidade` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` VARCHAR(2) NULL DEFAULT NULL,
  `Nome` VARCHAR(45) NULL DEFAULT ' ',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dados`.`motoristas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`motoristas` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NULL DEFAULT NULL,
  `CNH` VARCHAR(11) NULL DEFAULT NULL,
  `CatCNH` VARCHAR(1) NULL DEFAULT NULL,
  `ValCNH` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dados`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`veiculos` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NULL DEFAULT NULL,
  `Modelo` VARCHAR(45) NULL DEFAULT NULL,
  `Ano` INT(11) NULL DEFAULT NULL,
  `Placa` VARCHAR(8) NULL DEFAULT NULL,
  `Tipo` INT(11) NULL DEFAULT NULL,
  `QtdAssentos` INT(11) NULL DEFAULT NULL,
  `ValorDia` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dados`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dados`.`reservas` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_Cliente` INT(11) NULL DEFAULT NULL,
  `ID_LocalSaida` INT(11) NULL DEFAULT NULL,
  `ID_LocalDestino` INT(11) NULL DEFAULT NULL,
  `ID_Veiculo` INT(11) NULL DEFAULT NULL,
  `ID_MOTORISTA` INT(11) NULL DEFAULT NULL,
  `ID_Usuario` VARCHAR(12) NULL DEFAULT NULL,
  `DT_Saida` VARCHAR(40) NULL DEFAULT NULL,
  `DT_Retorno` VARCHAR(40) NULL DEFAULT NULL,
  `Valor` DECIMAL(15,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `clientes_ID_idx` (`ID_Cliente` ASC) VISIBLE,
  INDEX `localSaida_ID_idx` (`ID_LocalSaida` ASC) VISIBLE,
  INDEX `localDestino_ID_idx` (`ID_LocalDestino` ASC) VISIBLE,
  INDEX `veiculos_ID_idx` (`ID_Veiculo` ASC) VISIBLE,
  INDEX `motoristas_ID_idx` (`ID_MOTORISTA` ASC) VISIBLE,
  INDEX `usuarios_ID_idx` (`ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `clientes_ID`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `dados`.`clientes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localDestino_ID`
    FOREIGN KEY (`ID_LocalDestino`)
    REFERENCES `dados`.`locais` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `localSaida_ID`
    FOREIGN KEY (`ID_LocalSaida`)
    REFERENCES `dados`.`locais` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `motoristas_ID`
    FOREIGN KEY (`ID_MOTORISTA`)
    REFERENCES `dados`.`motoristas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarios_ID`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `dados`.`usuarios` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `veiculos_ID`
    FOREIGN KEY (`ID_Veiculo`)
    REFERENCES `dados`.`veiculos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
